### ISSUE TITLE
[Question] Is it possible to spawn multiple cars in the simulator?

### ISSUE THREAD

**Issue by FrancescoTerrosi** [tawnkramer/gym-donkeycar#10]
The title says it all, thank you :)

**Comment by tawnkramer** [comment]
https://github.com/tawnkramer/sdsandbox/blob/master/src/predict_server.py has
a --num_cars arg that will launch multiple cars.

**Comment by FrancescoTerrosi** [comment]
That's nice, but what about the possibility to launch 1 car controlled by the NN and the others controlled with PID controller?

**Comment by tawnkramer** [comment]
The networking model is switch now. This better accommodates clients in different processes with different settings.
