### ISSUE TITLE
Any docs on how to build a new track/env?

### ISSUE THREAD

**Issue by KingAndrew** [tawnkramer/gym-donkeycar#11]
I would like to make a series of different tracks but have no idea how to begin.
I'd be happy to contribute to the docs, write an article and provide examples if some one could point me in the right direction.

### Description
I would like to create more gym-donkeycar envs

```

**Comment by tawnkramer** [comment]
You can of course look at the code. There’s code there to create a track
based on a tiling road texture of your choosing.

If that’s outside your skill set, look at any Unity tutorial on how to
build a scene. If you make one and share it with me, I will add it to the
sim for you.

**Comment by KingAndrew** [comment]
Where is the code for the scenes you have in the simulator for gym-donkeycar?  I've tried with the sdsandbox repo following the [ More interesting worlds for sdsandbox](https://www.youtube.com/watch?v=oe7fYuYw8GY) example.  But I could not figure out how to get the Sim.exe to load those scenes.

**Comment by tawnkramer** [comment]
In the donkey branch
