### ISSUE TITLE
Can gym-sim drive with real tub photos?

### ISSUE THREAD

**Issue by RyanC1681** [tawnkramer/gym-donkeycar#13]
Can gym-sim drive with real tub photos?
i.e. python manage.py drive [--tub=<tub1,tub2,..tubn>] [--model=<model>] ## to import the real tub photo to drive then output pilot/angle', 'pilot/throttle to test if model works.

Thanks,

**Comment by tawnkramer** [comment]
Please see usage docs at
http://docs.donkeycar.com/guide/simulator/
