### ISSUE TITLE
[Question] How can I start with headless mode?

### ISSUE THREAD

**Issue by kinopiiiii** [tawnkramer/gym-donkeycar#14]
Does that need any configuration?
Thanks.

**Comment by tawnkramer** [comment]
Headless doesn’t work now.

**Comment by danielrich** [comment]
I have some time over the holidays. Any particular part at fault you can point me too and I can maybe throw some commits your way?

**Comment by tawnkramer** [comment]
Unity includes this command line option to run headless. So I exposed it.
But it crashes if you try to render anything. I don’t think you can fix.
It’s a Unity issue.
