### ISSUE TITLE
donkeycar simulation on windows

### ISSUE THREAD

**Issue by avncalst** [tawnkramer/gym-donkeycar#15]
* OpenAI Gym Environments for Donkey Carversion: donkey-generated-track-v0
* Python version: 3.7.2
* Operating System: windows 10, version 1903

### Description

Installed donkeycar 3.1.1, gym-donkeycar and donkeysimwindows

donkeycar works fine. donkeysimwindows works standalone. gym-donkeycar stops at "def wait_until_loaded(self)" in donkey_sim.py, outputting continuously "waiting for sim to start..". Looking with cmd "netstat -nbo" verified that connections were established. Connections timed out and new connections were established. Looking at the unitylog.txt revealed a read failure: A timeout has occurred while receiving a handshake. ---> System.IO.IOException: Read failure ---> System.Net.Sockets.SocketException: An established connection was aborted by the software in your host machine. See attached log file.

Any help would be much appreciated.
[unitylog.txt](https://github.com/tawnkramer/gym-donkeycar/files/4007208/unitylog.txt)

```
python manage.py drive
```

**Comment by tawnkramer** [comment]
Networking model switched now. Sim is server now.
