### ISSUE TITLE
Episode is endless because car is stuck on the track "donkey-mountain-track-v0"

### ISSUE THREAD

**Issue by AlexandrePoisson** [tawnkramer/gym-donkeycar#28]
* OpenAI Gym Environments for Donkey Car version: 
* Python version: 3.7 with tf 1.15
* Operating System: Ubuntu 20.04, venv with Python 3.7

### Description

I am trying to learn, using your PPO, on the brand new track: "donkey-mountain-track-v0"
But for each training, the car get stuck close to the track boundary.
![Screenshot from 2020-05-18 10-00-44](https://user-images.githubusercontent.com/13329302/82203768-091c7400-9904-11ea-9cdf-17c9025af797.png)

The episode is not stopped, so the car keep on doing some actions, but not enough to move away.
My analysis is that the issue is related to the command that stop the simulation. I can have a look at it but i will need some hints (look in the C# code, in the gym env.)
Potential solution is to rework the criteria that stop the episode: 

- stop episode after a certain time
- reduce the distance to the central line if this 
- stop when the car hits a wall
-... 

### What I Did
clone today's gym-donkeycar
pip install -e
use v2020.5.16 of the  https://github.com/tawnkramer/gym-donkeycar/releases/tag/v2020.5.16
start a training

```

No crash is happening, but i cannot train my RL Model
```

**Comment by philwinder** [comment]
I had this problem too. My workaround was to create a wrapper to limit the total number of time steps per episode. If it went over that, reset.

**Comment by tawnkramer** [comment]
We do issue events on lap completion now.

**Comment by tawnkramer** [comment]
checkpoint resets may help
