### ISSUE TITLE
gym env reset bug on windows

### ISSUE THREAD

**Issue by llucid-97** [tawnkramer/gym-donkeycar#30]
* OpenAI Gym Environments for Donkey Carversion: Windows simulator from May Race Edition v20.5.16  and gym wrapper from current latest commit (a3c4fcd)
* Python version: 3.6
* Operating System: Windows 10

### Description
When env.reset() is called, the car teleports back to the start, but keeps executing the last action taken for a few seconds before ceding control.
This means when trying to train the car with RL, the RL agent isn't actually starting from the start line; it often starts from a point where its already too late to not crash.

Here's the simplest code to reproduce the issue:
```python
import gym_donkeycar
import gym
import numpy as np
import time
#%% SET UP ENVIRONMENT
exe_path = r"C:\DonkeySimWin\donkey_sim.exe"
port = 9091

env = gym.make("donkey-warehouse-v0", exe_path=exe_path, port=port)

#%% PLAY
for t in range(100):
    obv = env.reset()
    done = False
    _ = env.step(np.array([0.0,0.0]))
    time.sleep(1)
    while not done:
        action = np.array([0.0,0.5]) # drive straight with small speed
        # execute the action
        obv, reward, done, info = env.step(action)
```

With this, I've set the agent to do nothing for 1 second right after reset, but when i run it, the car teleports to the start line and still drives off for a few seconds before the throttle gets set to 0.

### What I Did
I have a workaround, but it's not clean:

in **gym_donkeycar/envs/donkey_sim.py** : i modify the `reset` method of `DonkeyUnitySimHandler` to zero throttle and turn on brakes. Snippets are included below:
```python
 def reset(self):
        logger.debug("reseting")
        self.take_action([0.0, 0.0,1.0])
        time.sleep(0.5)
        self.send_reset_car()
        self.timer.reset()
        time.sleep(0.5)
        ...

# ----SNIP ----

    def take_action(self, action):
        try:
            brake = action[2]
        except IndexError:
            brake = 0.0
        self.send_control(action[0], action[1],brake)

        ...

# ----SNIP ----
    def send_control(self, steer, throttle, brake=0.0):
        if not self.loaded:
            return
        msg = {'msg_type': 'control', 'steering': steer.__str__(
        ), 'throttle': throttle.__str__(), 'brake': brake.__str__()}
        self.queue_message(msg)
```

Thought I'd put this up in case anyone else runs into this 👍

**Comment by tawnkramer** [comment]
That sounds about right. Unity Physx engine does not like objects getting
teleported and zero out vel. Internally I’m send reset for many frames.
Anyone have a cleaner way to fix?

**Comment by araffin** [comment]
>Anyone have a cleaner way to fix?

nope :/ doing the same here

**Comment by tungnd1705** [comment]
how did you guys resolve this? I have the same problem in ubuntu

**Comment by tawnkramer** [comment]
some people are leaving and entering the scene again to get a cleaner reset.

**Comment by tawnkramer** [comment]
that could be the key. perhaps destroying the car object and making a new one would cleanly reset the physics...
