### ISSUE TITLE
No module named picamera

### ISSUE THREAD

**Issue by Musclemanisme** [tawnkramer/gym-donkeycar#31]
How to configure my camera when I use donkeycar simulator on Ubuntu? I have followed guides on Donkeycar's home page. But there was an error that warned me 'No module named picamera'.
I am a greenhand.

Any help will be much appreciated!

**Comment by tawnkramer** [comment]
please take another look at the directions about setting options in
myconfig.py. It seems you haven't enabled DONKEY_GYM = True. So you may
have other problems if you skipped those steps.
