### ISSUE TITLE
Resize observation to bigger size

### ISSUE THREAD

**Issue by AlexKaravaev** [tawnkramer/gym-donkeycar#33]
* OpenAI Gym Environments for Donkey Carversion: Latest version
* Python version: 3.7
* Operating System: Ubuntu 18.04

### Description

When I am trying to upsize cam_resolution, image still comes in with (120,160,3) size.

### What I Did

I tried launching env with
```
cam_resolution=(590,1640,3)
```

Also tried to change in donkey_sim.py ```def send_cam_config``` to
```
def send_cam_config(self, img_w=0, img_h=0, img_d=0, img_enc=0, fov=0, fish_eye_x=0, fish_eye_y=0, offset_x=0, offset_y=0, offset_z=0, rot_x=0):
        msg = {"msg_type" : "cam_config",
               "fov" : str(fov),
               "fish_eye_x" : str(fish_eye_x),
               "fish_eye_y" : str(fish_eye_y),
               "img_w" : str(1640),
               "img_h" : str(590),
               "img_d" : str(img_d),
               "img_enc" : str(img_enc),
               "offset_x" : str(offset_x),
               "offset_y" : str(offset_y),
               "offset_z" : str(offset_z),
               "rot_x" : str(rot_x) }
        self.queue_message(msg)
        time.sleep(0.1)
```

The Unity window does change to the resolution I want, but observations are not.

**Comment by AlexKaravaev** [comment]
It's working, I was using different forked version.

**Comment by tungnd1705** [comment]
hi @AlexKaravaev , how do you resolve this? I did what you showed above but the observation is still (120,160,3)

**Comment by AlexKaravaev** [comment]
@tungnd1705 Well, I was using own forked version by mistake. 

When I am using the original repo version, it's enough to pass cam_size via constructor and the image comes with the size requested.

**Comment by tungnd1705** [comment]
I'm using the original repo version but still can not get a bigger obs size, it always returns (120,160,3) no matter what cam_resolution I put in the constructor. Can you show me your code?

**Comment by AlexKaravaev** [comment]
@tungnd1705  I looked it up, I think you must also call set_cam_config. Basically, you can take as an example this [script](https://github.com/tawnkramer/gym-donkeycar/blob/master/examples/test_cam_config.py).

**Comment by tungnd1705** [comment]
it works now, thanks!
