### ISSUE TITLE
How to render two images with different resolutions from one environment

### ISSUE THREAD

**Issue by tungnd1705** [tawnkramer/gym-donkeycar#34]
* OpenAI Gym Environments for Donkey Carversion:
* Python version:
* Operating System:

### Description

I am trying to create an environment but can return 2 different images when taking an action, these 2 images may have different resolutions

### What I Did

I checked the donkey_sim.py file but not sure how to do it yet. Any solutions?

**Comment by tawnkramer** [comment]
not possible now.
