### ISSUE TITLE
Environment seems broken

### ISSUE THREAD

**Issue by kritonpc** [tawnkramer/gym-donkeycar#40]
* OpenAI Gym Environments for Donkey Carversion: 1.0.15
* Python version: 3.7
* Operating System:Windows 10

### Description

So basically everything is broken. I'm trying to train with ddqn, but it doesn't seem to work at all. It seems like the speed is higher than in previous versions and the car only appears on the roads and mountain track map, while it doesn't work on the track map

**Comment by tawnkramer** [comment]
nice. very specific.

**Comment by kritonpc** [comment]
> nice. very specific.

What else would you like to know?
