### ISSUE TITLE
determining whether the car got to the end of the track?

### ISSUE THREAD

**Issue by 1337SEnergy** [tawnkramer/gym-donkeycar#41]
yeah, so...

is there any way to tell if the vehicle successfully got to the end of the track, for example donkey-generated-roads-v0 ? afaik I can only tell if they are off the road, but that doesn't mean that they actually finished the track

**Comment by tawnkramer** [comment]
Only on the mountain track now. There are checkpoint and lap finished
events.

**Comment by RealSEnergy** [comment]
how can I listen to these events? I can't find any documentation regarding those
