### ISSUE TITLE
Car can get off the generated road without triggering 'done' by reversing

### ISSUE THREAD

**Issue by 1337SEnergy** [tawnkramer/gym-donkeycar#42]
essentially, I assume you are calculating the CTE in just one dimension (perpendicular to the line in the middle), this, however, allows the vehicle (if you train it to control the throttle as well) to just get off the road without it triggering 'done'

![error](https://user-images.githubusercontent.com/18123409/89103443-50e66e00-d412-11ea-8997-6478d7f5d1b4.jpg)

**Comment by tawnkramer** [comment]
So you are welcome to over-ride the reward function with whatever you need.

**Comment by RealSEnergy** [comment]
I actually am overriding the reward function, the problem is the CTE calculations which are part of the sim, not the gym

**Comment by tawnkramer** [comment]
Maybe penalize negative velocity?

**Comment by RealSEnergy** [comment]
I also am doing that, however that still won't discourage the exploration action or the early NN state to reverse out of the road and add a state in the form of image above (look at the camera window) to the dataset, which is considered noise and doesn't help the network to converge at all

**Comment by RealSEnergy** [comment]
penalizing has no effect because of this: https://github.com/tawnkramer/gym-donkeycar/issues/43

**Comment by tawnkramer** [comment]
I think you can generate your own 'done' state based on whatever criteria you see fit.

**Comment by RealSEnergy** [comment]
you can, but as I said, it's not possible to determine whether the vehicle is actually off the road if it reverses at the beginning... why don't you just try it yourself instead of trying to argue with me here? I'm just trying to help you fix your bugs

and again, you never send any negative speed nor velocity, so penalizing it for reversing is not possible
