### ISSUE TITLE
Drive manually using keyboard

### ISSUE THREAD

**Issue by markub3327** [tawnkramer/gym-donkeycar#45]
### Description
  When we want to drive with simulated cars by keyboard, how can we read pushed/released keys? In OpenAI Gym environments exists `env.viewer.window.on_key_press = key_press` and `env.viewer.window.on_key_release = key_release`. After assigning own functions to these parameters of the environment, we can control what will be doing after push or release the key. 

```python
def key_press(k, mod):
    global exit_game
    global actions
    
    if k == key.ESCAPE: exit_game = True
    elif k == key.UP:    
        actions[3] = +1.0
        if actions[0] == 0.0 and actions[2] == 0.0:
            actions[1] = +1.0
    elif k == key.LEFT:  
        actions[0] = -1.0
        actions[1] =  0.0  # Cut gas while turning
    elif k == key.RIGHT: 
        actions[0] = +1.0
        actions[1] =  0.0  # Cut gas while turning
    elif k == key.DOWN:  
        actions[2] = +0.4  # stronger brakes
        actions[1] =  0.0  # Cut gas while braking

def key_release(k, mod):
    if k == key.LEFT and actions[0] == -1.0: 
        actions[0] = 0.0
        if actions[3] == 1.0:
            actions[1] = 1.0
    elif k == key.RIGHT and actions[0] == +1.0: 
        actions[0] = 0.0
        if actions[3] == 1.0:
            actions[1] = 1.0
    elif k == key.UP:    
        actions[1] = 0.0
        actions[3] = 0.0
    elif k == key.DOWN:  
        actions[2] = 0.0
```

**Comment by tawnkramer** [comment]
the keybaord provides a really bad learning signal. It's slow, and frustrating, and not worth your time, honestly. The step wise inputs do not give good labels and most NN fail to learn a good policy.

**Comment by markub3327** [comment]
Why will not the imitation learning works in this game? It's used for example in Unity + ML-Agents like [this](https://blogs.unity3d.com/2018/05/24/imitation-learning-in-unity-the-workflow/).
