### ISSUE TITLE
velocity kept after env.reset()

### ISSUE THREAD

**Issue by simeneide** [tawnkramer/gym-donkeycar#8]
* OpenAI Gym Environments for Donkey Carversion:
* Python version: 3.7
* Operating System: macOS

### Description
Seems like there is still some velocity left after resetting the environment. i.e. it still goes forward/turns after env.reset(). 

### What I Did

```
#%%
import os
import gym_donkeycar
import gym_donkeycar.envs
import gym
import numpy as np

#%% SET UP ENVIRONMENT
os.environ['DONKEY_SIM_PATH'] = "[...]/donkey_sim.app/Contents/MacOS/donkey_sim"
os.environ['DONKEY_SIM_PORT'] = str(9092)
os.environ['DONKEY_SIM_HEADLESS'] = str(0) # "1" is headless

env = gym.make("donkey-warehouse-v0")

#%%
action = np.array([0.0,4]) 
noaction = np.array([0.0,0.0]) 
for i in range(10):
    env.step(noaction)
    env.reset()
    for t in range(10):
        newobs, reward, done, info = env.step(action)
        if done:
            print("done err")
            env.reset()
            break

```

### Solution
The hack that seemed to do the trick was to reset the environment twice. Then, the remaining velocity is sucked into the temporary environment.

```
env.reset()
env.reset()
```

**Comment by tawnkramer** [comment]
that's Unity physics for you. Doesn't like getting reset.
