### ISSUE TITLE
PyPI version out of date

### ISSUE THREAD

**Issue by GershomA** [tawnkramer/gym-donkeycar#9]
* OpenAI Gym Environments for Donkey Carversion: 1.0.13
* Python version: 3.6 (anaconda env)
* Operating System: windows 10

### Description
The instructions on your readme.md say to use the pypi package, but this seems to be out of date wrt your github version: the current pypi version doesn't call the gym register functions in` __init__.py`, so `gym.make()` doesn't recognize any of the environments.
But the github version does, and everything works fine there.

### What I Did

I can workaround this by installing with `pip install git+https://github.com/tawnkramer/gym-donkeycar.git`, but this doesn't always work.

Could you please update the pypi version to match the github?

**Comment by ChunJyeBehBeh** [comment]
Hello, how you solve it at the end? I have the issue about `gym.error.UnregisteredEnv: No registered env with id: donkey-generated-track-v0`. I try to uninstall and install the gym again, but didn't solve the issue

**Comment by ihexx** [comment]
Couple things to check:
 - make sure you're importing gym before gym_donkeycar:
```python
import gym
import gym_donkeycar
```
- make sure you're using the git version. install with the command:
`pip install git+https://github.com/tawnkramer/gym-donkeycar.git` 

If you can't install the git version for some reason and you're stuck with the PyPI one, try:
```python
import gym_donkey.envs
```
If i remember correctly, the PyPI version put the function to register the gym environments in there

**Comment by ChunJyeBehBeh** [comment]
Hello, 

I think you mean `import gym_donkeycar.envs` and it solved my issue.

Although I cannot understand why and will try to figure the reason behind. Thanks for your help.

**Comment by ihexx** [comment]
yeah, my bad. typo.
each of those modules has a script called `__init__.py ` that is called when you import them.
The script is supposed to call a function that registers the donkey environments with gym so gym knows it exists when you call gym.make.
In the PyPI version, this was in the `.envs` submodule, but the author's moved it to the main module, but hasn't yet updated the PyPI one.
